[package]
name = "zenoh-action"
version = "0.0.1"
edition = "2021"

description = "Action server example using zenoh"
keywords = ["Zenoh", "Robotics"]
readme = "README.md"

[dependencies]
async-std = "1.12.0"
env_logger = "0.9.3"
log = "0.4.17"
log4rs = "1.2.0"
zenoh = "0.6.0-beta.1"
